### ISSUE TITLE
How to use locally with other gpt-LLMS s?

### ISSUE THREAD

**Issue by moebiussurfing** [linexjlin/GPTs#24]
Hey, 
thanks for that list!

sorry for the newbie question, 
but do you know if these prompts can be used in other chat engines?
the two that you liked (esperando and german seems too specific)

Something like orca or llama could used the prompts?
What others could you recommend?

Maybe it could be used downloading some model into the **LM Studio** app?

**Comment by FujiwaraChoki** [comment]
I like Vicuna 7B & Mistral 7B (new one) a lot. Vicuna is uncensored and won't bore you with it's responses. And Mistral's a very capable model overall.

**Comment by moebiussurfing** [comment]
Ok. Thanks.
But it seems that many of these leaked prompts are exclusive for paid gpt4...

**Comment by FujiwaraChoki** [comment]
> Ok. Thanks. But it seems that many of these leaked prompts are exclusive for paid gpt4...

You can use tools like [FreeGPTs](https://gpts.azen.app) to circumvent this :)

**Comment by moebiussurfing** [comment]
i don't have a paid account...
