### ISSUE TITLE
Cool website that allows you to use GPTs listed here for free!

### ISSUE THREAD

**Issue by FujiwaraChoki** [linexjlin/GPTs#29]
Here it is:

https://gpts.azen.app

Enjoy!!

**Comment by erkantaylan** [comment]
it is a phishing website probably. please someone remove this.

**Comment by FujiwaraChoki** [comment]
> it is a phishing website probably. please someone remove this.

![image](https://github.com/linexjlin/GPTs/assets/78088687/5922f9cb-e8e5-4ccc-a1e3-dfbe79ad8ae8)
What are you talking about?

**Comment by erkantaylan** [comment]
my bad. i guess there was something wrong with login page. it didn't work and looked fishy. sorry.

**Comment by FujiwaraChoki** [comment]
> my bad. i guess there was something wrong with login page. it didn't work and looked fishy also all other linkes, social media links etc did not work either. sorry. still though everything looks suspicious i wouldn't put my key there.

do what you want no one's forcing you 🤷
