### ISSUE TITLE
how to use them??? i am a free user

### ISSUE THREAD

**Issue by fisforfaheem** [linexjlin/GPTs#45]
it says wetong answers etc

**Comment by chu-obs** [comment]
Only open to plus users...

**Comment by arunsathiya** [comment]
>will we theoretically get the same results if we just copy and paste the text used to make the GPTs into our own free AI prompts?

I'd imagine there is a difference in quality of responses between GPT 3.5, which is what free users have access to, and GPT 4, which is what custom GPTs use.

**Comment by dtflare** [comment]
GPT 4 is not only higher quality, but its training set is as recent as April 2023, and what it doesn't know it can use RAG to search the internet and provide relevant responses. It is also a multimodal model meaning it can take images as input to produce text, or even other images. You can also use Dalle directly through ChatGPT4 which is awesome. Along with that you get these custom GPT's which will be the future 'AI app store' and you also get a suite of other tools developed and hosted by OpenAI.
I suggest looking at all your current subscriptions, getting rid of a few and investing in GPT4.

**Comment by findyourwings** [comment]
nice shill but yeah i definitely understand its capabilities

**Comment by dtflare** [comment]
So to answer your question no you won't get the same responses bc of the cut off date.
Prompt engineering could get a similar result, BUT the text you see to build the GPT's is only the original text that went into their design. GPTs are able to be refined over time which is pretty cool.

**Comment by fisforfaheem** [comment]
the answers are not worth it evrn after pastign this.. in chtgpt
