### ISSUE TITLE
Analyze all the prompts

### ISSUE THREAD

**Issue by grantjenks** [linexjlin/GPTs#53]
Great repository! The hundreds of prompts are really valuable for engineering with llms.

I wanted to analyze all the prompts so I fed them to GPT4 Turbo and generated a series of markdown files summarizing the various themes and prompt techniques used: https://github.com/grantjenks/gpt-prompt-notes

The markdown files are hosted statically at https://grantjenks.github.io/gpt-prompt-notes/ Would it be okay to create a PR linking to the analysis?

Thanks again!

**Comment by linexjlin** [comment]
This repo is dedicated to collecting leaked prompts to maintain simplicity and facilitate user contributions. If you aspire to analyze them or create a website with these prompts, that's an excellent idea! I can provide links to your site or project.

**Comment by 0xeb** [comment]
@grantjenks , check this out: https://github.com/LouisShark/chatgpt_system_prompt
