### ISSUE TITLE
这些设定应该怎么使用? 是填到创建GPT的instruction里吗?

### ISSUE THREAD

**Issue by gxagxagx** [linexjlin/GPTs#7]

**Comment by michaelskyba** [comment]
大多数 .md 文件都包含指向您可以使用的 GPT 的链接
![temp](https://github.com/linexjlin/GPTs/assets/57649592/ccb9e7fa-89fc-4c14-bb37-178151e2b8ce)

**Comment by gxagxagx** [comment]
谢谢回答, 我的意思是 我该如何用这个信息, 复制一个自己的GPT.

**Comment by michaelskyba** [comment]
我明白了，抱歉造成误会。

要将其复制为您自己的 GPT，您需要将 .md 文件中的说明复制粘贴到 GPT 编辑器的“Instructions”框中。 但是，并非所有这些都可以工作，因为某些 GPT 使用自定义操作和知识文件，而这些文件在此存储库中无法访问。
![temp](https://github.com/linexjlin/GPTs/assets/57649592/6fd08e15-5e6f-42be-a6ab-f395d12a0c1d)
