### ISSUE TITLE
Verifying correctness of the prompts

### ISSUE THREAD

**Issue by malusamayo** [linexjlin/GPTs#8]
Just curious, how were these prompts extracted?
Also, I'm wondering if there is a way to validate if these are the original prompt used in their GPTs?

**Comment by ruie** [comment]
They are original prompts and it is called prompt injection. Not all GPT instructions can be easily extracted now. They put instructions to not reveal them, you can still but you need to be creative in doing so.

**Comment by malusamayo** [comment]
That makes sense! I do wonder though, whether these extracted prompts may be inaccurate as LLMs are known to suffer from hallucinations?

**Comment by linexjlin** [comment]
There is no guarantee that these prompts are the original prompts, and these leaked prompts are for reference only.

**Comment by michaelskyba** [comment]
> That makes sense! I do wonder though, whether these extracted prompts may be inaccurate as LLMs are known to suffer from hallucinations?

When LLMs hallucinate, they generally don't make the exact same hallucination in every generation. So, if a GPT is consistently providing you with an identical prompt when fishing, you can be pretty confident that that prompt is accurate.
